import Head from "next/head";
import Swr from "../components/swr";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>SWR Example</h2>
        <Swr />
      </main>
    </div>
  );
}
